title: Pulsoid|Blog
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    has_social: true
    links:
      - new_window: true
        text: BRO plan
        url: 'https://pulsoid.net/pricing?from=blog'
  header:
    has_nav: false
    logo_img: /images/logo-main-256.png
    title: Pulsoid Blog
  layout_style: grid
  palette: green
menu:
  main:
    - identifier: Pricing
      name: Pricing
      url: 'https://pulsoid.net/pricing?from=blog'
disableKinds:
  - RSS
