title: Pulsoid|Blog
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    has_social: true
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    has_nav: true
    logo_img: /images/logo-main-256.png
    title: Ampersand
  layout_style: grid
  palette: green
disableKinds:
  - RSS
